name: Build and Push Docker image to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install Typescript
      run: npm install -g typescript
            
    - name: Build typescript
      run: tsc

    # - name: Add db url to env file
    #   run: echo "DB_URL=${{ secrets.DB_URL }}" > .env

    # - name: Add github token to env file
    #   run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> .env

    # - name: Add github email to env file
    #   run: echo "EMAIL=${{ secrets.EMAIL }}" >> .env  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # - name: Login to ACR
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ${{ secrets.ACR_LOGIN_SERVER }}
    #     username: ${{ secrets.ACR_USERNAME }}
    #     password: ${{ secrets.ACR_PASSWORD }}

    - name: Login to DOCKER HUB
      uses: docker/login-action@v1
      with:
        username: pikselas
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        # tags: ${{ secrets.ACR_LOGIN_SERVER }}/piblog:latest
        tags: https://hub.docker.com/repository/docker/pikselas/pikselasblog:latest